# Generated by Django 4.2.7 on 2024-02-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ManyToManyField(related_name="role", to="users.role"),
        ),
    ]
