# Generated by Django 4.2.7 on 2024-02-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("examp", "0004_alter_product_options_alter_gallery_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
