# Generated by Django 4.2.7 on 2024-02-28 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("examp", "0005_alter_shop_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="product", to="examp.product"
            ),
        ),
    ]
